# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metanet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import caffe2_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metanet.proto',
  package='caffe2',
  serialized_pb='\n\rmetanet.proto\x12\x06\x63\x61\x66\x66\x65\x32\x1a\x0c\x63\x61\x66\x66\x65\x32.proto\"{\n\tModelInfo\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x12\n\nmodelClass\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\'\n\rpredictorType\x18\x04 \x01(\t:\x10SINGLE_PREDICTOR\x12\x0f\n\x07modelId\x18\x05 \x01(\t\"&\n\x08\x42lobsMap\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x03(\t\"5\n\x07NetsMap\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x1d\n\x05value\x18\x02 \x02(\x0b\x32\x0e.caffe2.NetDef\"7\n\x08PlansMap\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x1e\n\x05value\x18\x02 \x02(\x0b\x32\x0f.caffe2.PlanDef\"\'\n\tStringMap\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\xc7\x01\n\nMetaNetDef\x12\x1f\n\x05\x62lobs\x18\x01 \x03(\x0b\x32\x10.caffe2.BlobsMap\x12\x1d\n\x04nets\x18\x02 \x03(\x0b\x32\x0f.caffe2.NetsMap\x12$\n\tmodelInfo\x18\x03 \x01(\x0b\x32\x11.caffe2.ModelInfo\x12\x1f\n\x05plans\x18\x04 \x03(\x0b\x32\x10.caffe2.PlansMap\x12\x32\n\x17\x61pplicationSpecificInfo\x18\x05 \x03(\x0b\x32\x11.caffe2.StringMap')




_MODELINFO = _descriptor.Descriptor(
  name='ModelInfo',
  full_name='caffe2.ModelInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='caffe2.ModelInfo.project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelClass', full_name='caffe2.ModelInfo.modelClass', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='caffe2.ModelInfo.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='predictorType', full_name='caffe2.ModelInfo.predictorType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("SINGLE_PREDICTOR", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelId', full_name='caffe2.ModelInfo.modelId', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=162,
)


_BLOBSMAP = _descriptor.Descriptor(
  name='BlobsMap',
  full_name='caffe2.BlobsMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='caffe2.BlobsMap.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='caffe2.BlobsMap.value', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=164,
  serialized_end=202,
)


_NETSMAP = _descriptor.Descriptor(
  name='NetsMap',
  full_name='caffe2.NetsMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='caffe2.NetsMap.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='caffe2.NetsMap.value', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=204,
  serialized_end=257,
)


_PLANSMAP = _descriptor.Descriptor(
  name='PlansMap',
  full_name='caffe2.PlansMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='caffe2.PlansMap.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='caffe2.PlansMap.value', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=259,
  serialized_end=314,
)


_STRINGMAP = _descriptor.Descriptor(
  name='StringMap',
  full_name='caffe2.StringMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='caffe2.StringMap.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='caffe2.StringMap.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=316,
  serialized_end=355,
)


_METANETDEF = _descriptor.Descriptor(
  name='MetaNetDef',
  full_name='caffe2.MetaNetDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blobs', full_name='caffe2.MetaNetDef.blobs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nets', full_name='caffe2.MetaNetDef.nets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modelInfo', full_name='caffe2.MetaNetDef.modelInfo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='plans', full_name='caffe2.MetaNetDef.plans', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applicationSpecificInfo', full_name='caffe2.MetaNetDef.applicationSpecificInfo', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=358,
  serialized_end=557,
)

_NETSMAP.fields_by_name['value'].message_type = caffe2_pb2._NETDEF
_PLANSMAP.fields_by_name['value'].message_type = caffe2_pb2._PLANDEF
_METANETDEF.fields_by_name['blobs'].message_type = _BLOBSMAP
_METANETDEF.fields_by_name['nets'].message_type = _NETSMAP
_METANETDEF.fields_by_name['modelInfo'].message_type = _MODELINFO
_METANETDEF.fields_by_name['plans'].message_type = _PLANSMAP
_METANETDEF.fields_by_name['applicationSpecificInfo'].message_type = _STRINGMAP
DESCRIPTOR.message_types_by_name['ModelInfo'] = _MODELINFO
DESCRIPTOR.message_types_by_name['BlobsMap'] = _BLOBSMAP
DESCRIPTOR.message_types_by_name['NetsMap'] = _NETSMAP
DESCRIPTOR.message_types_by_name['PlansMap'] = _PLANSMAP
DESCRIPTOR.message_types_by_name['StringMap'] = _STRINGMAP
DESCRIPTOR.message_types_by_name['MetaNetDef'] = _METANETDEF

class ModelInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODELINFO

  # @@protoc_insertion_point(class_scope:caffe2.ModelInfo)

class BlobsMap(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOBSMAP

  # @@protoc_insertion_point(class_scope:caffe2.BlobsMap)

class NetsMap(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NETSMAP

  # @@protoc_insertion_point(class_scope:caffe2.NetsMap)

class PlansMap(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PLANSMAP

  # @@protoc_insertion_point(class_scope:caffe2.PlansMap)

class StringMap(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRINGMAP

  # @@protoc_insertion_point(class_scope:caffe2.StringMap)

class MetaNetDef(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _METANETDEF

  # @@protoc_insertion_point(class_scope:caffe2.MetaNetDef)


# @@protoc_insertion_point(module_scope)
